//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowAndReturn
    {
        public int BID { get; set; }
        public Nullable<int> EID { get; set; }
        public string BPMan { get; set; }
        public Nullable<int> BBrandID { get; set; }
        public Nullable<int> BHour { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
        public int EStateID { get; set; }
        public Nullable<int> EType { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual EType EType1 { get; set; }
        public virtual State State { get; set; }
    }
}
