//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.BorrowAndReturn = new HashSet<BorrowAndReturn>();
            this.Reject = new HashSet<Reject>();
            this.Service = new HashSet<Service>();
        }
    
        public int EID { get; set; }
        public string EName { get; set; }
        public Nullable<int> ETypeID { get; set; }
        public string EModel { get; set; }
        public string EBrand { get; set; }
        public string ENum { get; set; }
        public string EFactory { get; set; }
        public Nullable<System.DateTime> EMFD { get; set; }
        public Nullable<System.DateTime> EBD { get; set; }
        public string EPic { get; set; }
        public string EDesc { get; set; }
        public int EState { get; set; }
    
        public virtual ICollection<BorrowAndReturn> BorrowAndReturn { get; set; }
        public virtual EType EType { get; set; }
        public virtual ICollection<Reject> Reject { get; set; }
        public virtual ICollection<Service> Service { get; set; }
    }
}
