//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EquipmentDBEntities : DbContext
    {
        public EquipmentDBEntities()
            : base("name=EquipmentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BorrowAndReturn> BorrowAndReturn { get; set; }
        public DbSet<Brand> Brand { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<EType> EType { get; set; }
        public DbSet<Reject> Reject { get; set; }
        public DbSet<Service> Service { get; set; }
        public DbSet<State> State { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
