//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reject
    {
        public int RID { get; set; }
        public int EID { get; set; }
        public Nullable<decimal> RCost { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
        public string RCause { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
