//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int SID { get; set; }
        public int EID { get; set; }
        public string SPMan { get; set; }
        public string SAddress { get; set; }
        public string SCause { get; set; }
        public Nullable<System.DateTime> SCauseDate { get; set; }
        public string SDesc { get; set; }
        public string SCost { get; set; }
        public Nullable<decimal> SHour { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
